name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  sample_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: echo "Sample Workflow"
